"""Executable public contracts shared across MyClaw runtime boundaries."""

from myclaw.contracts.common import format_rfc3339_milliseconds, make_session_id
from myclaw.contracts.errors import STABLE_ERROR_CODES, ErrorCode, ErrorInfo, ModelCallError
from myclaw.contracts.events import (
    AgentEvent,
    AgentEventPayload,
    AgentEventType,
    BackgroundCompletedPayload,
    PermissionRequestedPayload,
    ProgressPayload,
    TextDeltaPayload,
    ToolCompletedPayload,
    ToolStartedPayload,
    TurnCancelledPayload,
    TurnCompletedPayload,
    TurnFailedPayload,
    TurnStartedPayload,
    validate_agent_event_sequence,
)
from myclaw.contracts.json_types import JsonObject, JsonScalar, JsonValue
from myclaw.contracts.management import ConfigView, MemoryTaskResult, ResumeResult, RuntimeStatus
from myclaw.contracts.memory import SummaryEntry
from myclaw.contracts.models import (
    AssistantModelMessage,
    FinishReason,
    ModelCompleted,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ModelRoute,
    ModelStreamEvent,
    ModelToolCall,
    ModelUsage,
    ReasoningEffort,
    TextDelta,
    ToolModelMessage,
    UserModelMessage,
    validate_model_stream_events,
)
from myclaw.contracts.ports import (
    ConversationPort,
    ManagementPort,
    MemoryStore,
    ModelProvider,
    SessionStore,
    SummaryStore,
    Tool,
)
from myclaw.contracts.scheduling import ScheduledWork, serialize_scheduled_work
from myclaw.contracts.sessions import (
    AssistantMessageStatus,
    AssistantSessionMessage,
    ConversationSession,
    CumulativeUsage,
    MetadataUpdate,
    SessionError,
    SessionMessage,
    SessionMetadata,
    SessionSummary,
    ToolSessionMessage,
    UserSessionMessage,
)
from myclaw.contracts.tools import (
    ArtifactReference,
    PermissionDecision,
    ToolDefinition,
    ToolExecutionContext,
    ToolExecutionLane,
    ToolResult,
    ToolResultStatus,
)

__all__ = [
    "STABLE_ERROR_CODES",
    "AgentEvent",
    "AgentEventPayload",
    "AgentEventType",
    "ArtifactReference",
    "AssistantMessageStatus",
    "AssistantModelMessage",
    "AssistantSessionMessage",
    "BackgroundCompletedPayload",
    "ConfigView",
    "ConversationPort",
    "ConversationSession",
    "CumulativeUsage",
    "ErrorCode",
    "ErrorInfo",
    "FinishReason",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "ManagementPort",
    "MemoryStore",
    "MemoryTaskResult",
    "MetadataUpdate",
    "ModelCallError",
    "ModelCompleted",
    "ModelMessage",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "ModelRoute",
    "ModelStreamEvent",
    "ModelToolCall",
    "ModelUsage",
    "PermissionDecision",
    "PermissionRequestedPayload",
    "ProgressPayload",
    "ReasoningEffort",
    "ResumeResult",
    "RuntimeStatus",
    "ScheduledWork",
    "SessionError",
    "SessionMessage",
    "SessionMetadata",
    "SessionStore",
    "SessionSummary",
    "SummaryEntry",
    "SummaryStore",
    "TextDelta",
    "TextDeltaPayload",
    "Tool",
    "ToolCompletedPayload",
    "ToolDefinition",
    "ToolExecutionContext",
    "ToolExecutionLane",
    "ToolModelMessage",
    "ToolResult",
    "ToolResultStatus",
    "ToolSessionMessage",
    "ToolStartedPayload",
    "TurnCancelledPayload",
    "TurnCompletedPayload",
    "TurnFailedPayload",
    "TurnStartedPayload",
    "UserModelMessage",
    "UserSessionMessage",
    "format_rfc3339_milliseconds",
    "make_session_id",
    "serialize_scheduled_work",
    "validate_agent_event_sequence",
    "validate_model_stream_events",
]
